# Copyright (c) 2020 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

title: "Kickstart Application Deployments"
description: "The kickstart framwork creates a foundation for application deployments in Oracle Cloud Infrastructure"
informationalText: "This stack helps operators to set up a hosting environment for enterprise applications in Oracle Cloud Infrastructure (OCI). A base set of resources is provisioned and configured."
schemaVersion: 1.1.0
version: "20210611"
locale: "en"

variableGroups:
- title: "Region"
  visible: true
  variables:
  - region

- title: "Service"
  visible: true
  variables:
  - parent
  - compartment_ocid
  - current_user_ocid
  - organization
  - solution
  - owner
  - repository

- title: "Limits"
  visible: true
  variables:
  - tenancy_ocid
  - class

- title: "Lifecycle"
  visible: true
  variables:
  - stage

- title: "Application Type"
  visible: true
  variables:
  - host
  - nodes
  - container

- title: "Database"
  visible: true
  variables:
  - create_adb
  - adb_type

- title: "Network"
  visible: true
  variables:
  - netsettings
  - internet
  - osn
  - nat
  - ipv6

- title: "Wallet"
  visible: true
  variables:
  - create_wallet
  - wallet_type

variables:
# Tenancy
  tenancy_ocid:
    title: "Tenancy ID"
    description: "The Oracle Cloud Identifier for your tenancy"
    visible: false
    type: string
    required: true

  class:
    title: "Contract Type"
    description: "Selecting the Universal Credit Consumption (UCC) Model preselects appropriate resource types"
    type: enum
    default: "FREE_TIER"
    required: true
    enum:
      - FREE_TIER
      - TRIAL
      - PAYG
      - UCC

# Service Configuration
  compartment_ocid:
    title: "Compartment ID"
    description: "The Oracle Cloud Identifier for your compartment"
    visible: false
    type: string
    required: true
  
  current_user_ocid:
    title: "User ID"
    description: "The Oracle Cloud Identifier for the current user"
    visible: false
    type: string
    required: true
    
  parent:
    title: "Parent Compartment"
    description: "The Oracle Cloud Identifier for the root compartment. The default should only be changed by experienced users."
    type: oci:identity:compartment:id
    visible: false
    dependsOn:
      compartmentId: tenancy_ocid
      accessLevel: ANY
      lifecycleState: ACTIVE
    required: true

  region:
    title: "Region"
    description: "The Oracle Cloud Identifier the target region"
    visible: true
    type: oci:identity:region:name
    required: true

  organization:
    title: "Organization"
    description: "Identifier for the organization, owning the service"
    type: string
    default: "Organization"
    minLength: 1
    maxLength: 25
    pattern: "^[a-zA-Z]+$"
    required: true

  solution:
    title: "Solution"
    description: "Identifier for the service, the name should be unique within the tenancy"
    type: string
    default: "Name"
    minLength: 1
    maxLength: 25
    pattern: "^[a-zA-Z]+$"
    required: true

  stage:
    title: "Lifecycle Stage"
    description: "Selecting the lifecycle stage preselects an appropriate collection of operational controls"
    type: enum
    default: "DEV"
    required: true
    enum:
      - DEV
      - UAT
      - PROD

  repository:
    title: "Repository"
    description: "Provide an URL for the code source"
    type: string
    required: false

  owner:
    title: "Administrator"
    description: "Provide an eMail address for the technical administrator"
    type: string
    required: true

# Application Type
  host:
    type: boolean
    title: "Enterprise Application"
    required: false

  nodes:
    type: boolean
    title: "Web Application"
    required: false

  container:
    type: boolean
    title: "Cloud Native Service"
    required: false

# Network Options
  netsettings:
    type: boolean
    title: "Advanced Network Settings"
    required: true
    default: false

  internet:
    type: enum
    title: "Network Access:"
    required: true
    visible: netsettings
    enum:
      - PUBLIC
      - PRIVATE

  ipv6:
    type: boolean
    title: "IPv6"
    required: true
    visible: netsettings
    default: false

  nat:
    type: boolean
    title: "NAT for Private Subnets"
    required: true
    visible: netsettings
    default: true

  osn:
    type: enum
    title: "Oracle Cloud Services:"
    required: true
    visible: netsettings
    enum:
      - ALL_SERVICES
      - OBJECT_STORAGE
      - DISABLE

# Database Service
  create_adb:
    type: boolean
    title: "Create an Autonomous Database"
    required: false

  adb_type:
    title: "Database Type"
    visible: create_adb
    required: false
    type: enum
    enum:
      - TRANSACTION_PROCESSING
      - APEX
      - DATA_WAREHOUSE
      - JSON

# Encryption Service
  create_wallet:
    type: boolean
    title: "Create a Wallet"
    required: false

  wallet_type:
    title: "Vault Type"
    visible: create_wallet
    required: false
    type: enum
    enum:
      - Software
      - HSM