# Copyright (c) 2020 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.


title: "oCloud Framwork: Service Residency"
description: "The landing zone template creates a foundation for application deployments in Oracle Cloud Infrastructure"
informationalText: "The 'ocloud' framework helps operators to set up a hosting environment for enterprise applications in Oracle Cloud Infrastructure (OCI). A base set of resources is provisioned and configured. This framework aims to ease migrations for enterprise applications."
schemaVersion: 1.1.0
version: "20210611"
locale: "en"

variableGroups:
- title: "Stack Identifier"
  visible: false
  variables:
  - tenancy_ocid
  - compartment_ocid
  - region
  - current_user_ocid
  
- title: "Service Configuration"
  visible: true
  variables:
  - organization
  - solution
  - class
  - stage

- title: "Operator Details"
  visible: true
  variables:
  - owner
  - repository

- title: "Teancy Configuration"
  visible: false
  variables:
  - domains
  - segments

variables:
  tenancy_ocid:
    title: "Tenancy ID"
    description: "The Oracle Cloud Identifier for your tenancy"
    type: string
    required: true

  compartment_ocid:
    title: "Compartment ID"
    description: "The Oracle Cloud Identifier for your compartment"
    type: string
    required: true

  region:
    title: "Home Region"
    description: "The Oracle Cloud Identifier for your home region"
    type: string
    required: true
  
  current_user_ocid:
    title: "User ID"
    description: "The Oracle Cloud Identifier for the current user"
    type: string
    required: true

  organization:
    title: "Organization"
    description: "Identifier for the organization or platform owner"
    type: string
    required: true

  solution:
    title: "Service Name"
    description: "Identifier for the service delivery platform"
    type: string
    required: true

  stage:
    title: "Lifecycle Stage"
    description: "Define the CI/CD process stage, e.g. dev, uat, prod"
    type: enum
    default: "DEV"
    required: true
    enum:
      - DEV
      - TEST
      - PROD
  
  class:
    title: "Classification"
    description: "Define the resource bundle to be provisioned"
    type: enum
    default: "enterprise"
    required: true
    enum:
      - free_tier
      - paid
      - enterprise
      - premium



  repository:
    title: "Source Code URL"
    description: "Provide an URL to your IaC repository"
    type: string
    default: "https://gitlab.com/infracoding/brose_blockchain"
    required: false

  owner:
    title: "Service Owner"
    description: "Provide an eMail address for the technical administrator of your project"
    type: string
    required: true
  
  domains:
    title: "Administrator Domains"
    description: "Enabling a seperation of concerns"
    type: string
    required: true

  segments:
    title: "Network Segments"
    description: "Defining a network topology"
    type: string
    required: true