// Copyright (c) 2020 Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

== Requirements

Define an link:/init.tf[encapsulating compartment].

== Providers

[cols="a,a",options="header,autowidth"]
|===
|Name |Version
|[[provider_oci]] <<provider_oci,oci>> |n/a
|[[provider_null]] <<provider_null,null>> |n/a
|[[provider_time]] <<provider_time,time>> |n/a
|===

== Module
```hcl
module "operation_section" {
  depends_on = [ oci_identity_compartment.init ]
  source = "./component/admin_section/"
  providers      = { oci = oci.home }
  config = {
    tenancy_id    = var.tenancy_ocid
    source        = var.bundle_types["${var.bundle}"]
    display_name  = lower("${local.service_name}_${var.operation}")
    freeform_tags = { 
      "framework" = "ocloud"
    }
  }
  compartment  = {
    # Enable compartment delete on destroy. If true, compartment will be deleted when terraform destroy is executed
    enable_delete = true
    parent        = local.service_id
  }
  roles = {
    "${local.service_name}_administrator"  = [
      "ALLOW GROUP ${local.service_name}_administrator to read users in compartment ${local.service_name}",
      "ALLOW GROUP ${local.service_name}_administrator to read groups in compartment ${local.service_name}",
      "ALLOW GROUP ${local.service_name}_administrator to manage users in compartment ${local.service_name}",
      "ALLOW GROUP ${local.service_name}_administrator to manage groups in compartment ${local.service_name} where target.group.name = '${local.service_name}_administrator'",
      "ALLOW GROUP ${local.service_name}_administrator to manage groups in compartment ${local.service_name} where target.group.name = '${local.service_name}_secops'",
    ]
  }
}
```

== Resources

[cols="a,a",options="header,autowidth"]
|===
|Name |Type
|https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/identity_compartment[oci_identity_compartment.section] |resource
|https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/identity_group[oci_identity_group.section] |resource
|https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/identity_policy[oci_identity_policy.section] |resource
|https://registry.terraform.io/providers/hashicorp/oci/latest/docs/data-sources/identity_compartments[oci_identity_compartments.section] |data source
|https://registry.terraform.io/providers/hashicorp/oci/latest/docs/data-sources/identity_policies[oci_identity_policies.section] |data source
|https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/sleep[time_sleep.wait] |resource
|https://registry.terraform.io/providers/hashicorp/null/latest/docs/resources/resource[null_resource.previous] |resource
|===

== Inputs

[cols="a,a,a,a,a",options="header,autowidth"]
|===
|Name |Description |Type |Default |Required
|[[input_config]] <<input_config,config>>
|Settings for adminstrator section
|

[source]
----
object({
    tenancy_id    = string,
    source        = string,
    display_name  = string,
    freeform_tags = map(any)
  })
----

|n/a
|yes

|[[input_compartment]] <<input_compartment,compartment>>
|Settings for compartment
|

[source]
----
object({
    enable_delete = bool,
    parent        = string
  })
----

|n/a
|yes

|[[input_roles]] <<input_roles,roles>>
|Role definitions
|`map(list(any))`
|n/a
|yes

|===

Parameter definitions can be found in the link:/doc/glossary.adoc[glossary]

== Outputs

[cols="a,a",options="header,autowidth"]
|===
|Name |Description
|[[output_compartment_id]] <<output_compartment_id,compartment_id>> |compartment details
|[[output_compartment_name]] <<output_compartment_name,compartment_name>> |compartment details
|[[output_roles]] <<output_roles,roles>> |administrator roles
|===
