# Title shown in Application Information tab.
title: "Database as a Service on VM Schema"
# Sub Title shown in Application Information tab.
description: "" 
informationalText: "The Stack deploys a Database System on VM with a single pluggable Database.
A set of three configuration templates are available for typical Database System installation use cases. Small: 19c Oracle Enterprise Edition, Single-Node, 2 OCPUs and 512 GB Storage
, Medium: 19c Oracle Enterprise Edition, Single-Node, 8 OCPUs and 4 TB Storage and Large: 19c Oracle Enterprise Edition, Single-Node, 16 OCPUs and 8 TB Storage.
Refer to the Database as a Service on VM stack documentation for further options."

schemaVersion: 1.0.0
version: "20210721"

# URL of Logo Icon used on Application Information tab. Logo must be 130x130 pixels.
# (Optional)
# logoUrl: https://cloudmarketplace.oracle.com/marketplace/content?contentId=53066708

# Used in Application Information tab to Hyperlink Title and Logo to the Marketplace 
# Listing.
# Also used to link to Listing Usage section for "View Instructions".
# (Optional) If it is missing, Application Information uses the 
# "marketplace-listing-id" tag for the same purpose.
# source:
#   type: marketplace
#   reference: 16132843

locale: "en"
variableGroups:
  - title: "Basic Database System Configuration"
    variables:
      - ${service}
      - ${db_system_display_name}
      - ${db_system_db_home_database_db_name}
      - ${db_system_db_home_display_name}
      - ${db_system_db_home_database_pdb_name}
      - ${db_config}
      - ${deployment_type}

  - title: "Database Administrator Credentails"
    variables:
      - ${db_system_db_home_database_admin_password}
      - ${optional_tde_wallet_password}
      - ${db_system_db_home_database_tde_wallet_password}

  - title: "Add ssh Public key"
    variables:
      - ${db_system_ssh_public_keys}

  - title: "Select a Shape"
    visible: 
      eq:
        - db_config
        - "Custom"
    variables:
    - ${db_system_shape}

  - title: "DB System Configuration"
    visible: 
      eq:
        - db_config
        - "Custom"
    variables:
      - ${compartment_id}
      - ${availability_domains}
      - ${db_system_node_count}
      - ${db_system_cluster_name}
      - ${db_system_database_edition}
      - ${db_system_db_home_db_version}

  - title: "Storage management software"
    visible: 
      eq:
        - db_config
        - "Custom"
    variables:
      - ${db_system_db_system_options_storage_management}
      
  - title: "Storage"
    visible: 
      eq:
        - db_config
        - "Custom"
    variables:
      - ${db_system_data_storage_size_in_gb}

  - title: "Workload Type"
    visible: 
      eq:
        - db_config
        - "Custom"
    variables:
      - ${db_system_db_home_database_db_workload}

#  - title: "Database Information"
#    visible: 
#      eq:
#        - db_config
#        - "Custom"
#    variables:
#      - ${db_system_db_home_database_db_name}
#      - ${db_system_db_home_display_name}
#      - ${db_system_db_home_db_version}
#      - ${db_system_db_home_database_pdb_name}

  - title: "Configure Database Backups"
    visible: 
      eq:
        - db_config
        - "Custom"
    variables:
      - ${db_system_db_home_database_db_backup_config_auto_backup_enabled}
      - ${db_system_db_home_database_db_backup_config_auto_backup_window}
      - ${db_system_db_home_database_db_backup_config_recovery_window_in_days}
    
  - title: "License Type"
    visible: 
      eq:
        - db_config
        - "Custom"
    variables:
      - ${db_system_license_model}

  - title: "Network Information"
    visible: 
      eq:
        - db_config
        - "Custom"
    variables:
      - ${nw_compartment_id}
      - ${vcn_id}
      - ${subnet_id}
      - ${db_system_nsg_id}
      - ${db_system_hostname}
      - ${db_system_private_ip}

  - title: "Advanced Options"
    visible: 
      eq:
        - db_config
        - "Custom"
    variables:
      - ${db_system_fault_domains}
      - ${db_system_time_zone}

  - title: "Management"
    visible: 
      eq:
        - db_config
        - "Custom"
    variables:
      - ${db_system_db_home_database_character_set}
      - ${db_system_db_home_database_ncharacter_set}

  - title: "Hidden Variables"
    visible: false
    variables:
      - "tenancy_ocid"
      - "user_ocid"
      - "fingerprint"
      - "private_key_path"
      - "region"
      - "db_system_source"
      - ${db_system_db_home_database_defined_tags}
      - ${db_system_db_home_database_freeform_tags}
      - ${db_system_db_home_defined_tags}
      - ${db_system_defined_tags}

variables:

  db_config:
    title: "DBaaS on VM Standard Configurations"
    description: "Small - 2 OCPUs and 512 GB Storage, Medium 8 OCPUs and 4 TB Storage, Large 16 OCPUs and 8 TB Storage"
    type: enum
    enum:
      - Small
      - Medium
      - Large
      - Custom
    default: Small

  deployment_type:
    title: "Deployment Type"
    description: "Fast Provisioning - LVM, single-node, automated backups disabled; Non High Availibility - ASM, single-node, automated backups enabled; High Availibility - ASM, dual-node, automated backups enabled. This option has no effect if Custom Configuration has been selected."
    type: enum
    enum:
      - "Fast Provisioning"
      - "Basic"
      - "Cluster"
    default: ""

  compartment_id:
    title: "Database Compartment"
    type: oci:identity:compartment:id

  service:
    title: "Service Label"
    type: string
    description: "Common Service Label to deploy DB to CIS Landing Zone"
    required: true

  db_system_display_name:
    title: "Database System Name"
    type: string
    description: "The user-friendly name for the DB system. The name does not have to be unique"
    required: true

  availability_domains:
    title: "Availability Domain"
    type: oci:identity:availabilitydomain:name
    description: "Availability domain where the DB system is located"
    dependsOn:
      compartmentId: ${compartment_ocid}

  db_system_fault_domains:
    title: "Fault Domains"
    description: "Leave empty for Oracle to pick the best fault-domain choice, or enter one fault-domain for a single node instance or two for a two node DB System, valid values are FAULT-DOMAIN-1, FAULT-DOMAIN-2 and FAULT-DOMAIN-3"
    type: array
    items:
      type: string
      pattern: "^FAULT-DOMAIN-([1-3]+)$"
    minItems: 0
    maxItems: 2
    uniqueItems: true

  db_system_shape:
    title: "Shape Type"
    type: oci:core:instanceshape:name
    dependsOn:
      compartmentId: ${compartment_ocid}

  db_system_node_count:
    title: "Total node count"
    type: integer
    minimum: 1
    maximum: 2
    default: 1

  db_system_database_edition:
    title: "Oracle Database software edition"
    description: "For 2-node clusters, ENTERPRISE_EDITION_EXTREME_PERFORMANCE is automatically selected"
    type: enum
    enum:
      - "STANDARD_EDITION"
      - "ENTERPRISE_EDITION"
      - "ENTERPRISE_EDITION_HIGH_PERFORMANCE"
      - "ENTERPRISE_EDITION_EXTREME_PERFORMANCE"
    default: ENTERPRISE_EDITION

  db_system_db_system_options_storage_management:
    title: "Storage option used in DB system"
    description: "The storage option used in DB system. ASM - Automatic storage management LVM - Logical Volume management. For a quick deployment use LVM. 2-node instances require to use ASM."
    type: enum
    enum:
      - ASM
      - LVM
    default: ASM

  db_system_data_storage_size_in_gb:
    title: "Initial data volume size (in GB)"
    type: enum
    description: "Size (in GB) of the initial data volume that will be created and attached to a virtual machine DB system"
    enum:
      - 256
      - 512
      - 1024
      - 2048
      - 4096
      - 6144
      - 8192
      - 10240
      - 12288
      - 14336
      - 16384
      - 18432
      - 20480
      - 22528
      - 24576
      - 26624
      - 28672
      - 30720
      - 32768
      - 34816
      - 36864
      - 38912
      - 40960
    default: 512


  db_system_cluster_name:
    title: "Cluster Name"
    type: string
    visible:
      gt:
        - ${db_system_node_count}
        - 1

  db_system_ssh_public_keys:
    title: "Public key for SSH access to the DB system"
    type: oci:core:ssh:publickey

  db_system_license_model:
    title: "License Type"
    type: enum
    enum:
      - LICENSE_INCLUDED
      - BRING_YOUR_OWN_LICENSE
    default: LICENSE_INCLUDED

# networking parameters

  nw_compartment_id:
    title: "Network Compartment OCID"
    type: oci:identity:compartment:id

  vcn_id:
    title: "Database Client VCN"
    type: oci:core:vcn:id
    description: "VNC where the database client will be created"
    dependsOn:
      compartmentId: ${nw_compartment_id}
  
  subnet_id:
    title: "Database Client Subnet"
    type: oci:core:subnet:id
    description: "Do not use a subnet that overlaps with 192.168.16.16/28, which is used by the Oracle Clusterware private interconnect on the database instance"
    dependsOn:
      compartmentId: ${nw_compartment_id}
      vcnId: ${vcn_id}
      hidePublicSubnet: true

  db_system_nsg_id:
    title: "Database Network Security Group"
    type: oci:core:nsg:id
    dependsOn:
      vcnId: ${vcn_id}
      compartmentId: ${nw_compartment_id}

  db_system_hostname:
    title: "Hostname Prefix"
    type: string
    description: "The hostname for the DB system. The hostname must begin with an alphabetic character, and can contain alphanumeric characters and hyphens (-). The maximum length of the hostname is 16 characters for bare metal and virtual machine DB systems, and 12 characters for Exadata DB systems. The maximum length of the combined hostname and domain is 63 characters. Note: The hostname must be unique within the subnet. If it is not unique, the DB system will fail to provision"

  db_system_private_ip:
    title: "Private IP address"
    type: string
    description: "A private IP address of your choice. Must be an available IP address within the subnet's CIDR. If you don't specify a value, Oracle automatically assigns a private IP address from the subnet. Supported for VM BM shape"
    pattern: "^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$"

  db_system_time_zone:
    title: "Time Zone"
    type: enum
    enum:
      - UTC
      - Europe/Berlin
    default: UTC

  db_system_db_home_database_db_name:
    title: "Database Name"
    type: string
    description: "The display name of the database to be created from the backup. It must begin with an alphabetic character and can contain a maximum of eight alphanumeric characters. Special characters are not permitted."
    default: "cdb01"
    required: true
  
  db_system_db_home_display_name:
    title: "User-provided name of Database Home"
    type: string
    description: "The user-provided name of the Database Home"
    default: "dbhome"
    required: true

  db_system_db_home_database_pdb_name:
    title: "Pluggable Database Name"
    description: "The name of the pluggable database. The name must begin with an alphabetic character and can contain a maximum of thirty alphanumeric characters. Special characters are not permitted. Pluggable database should not be same as database name"
    type: string
    default: "pdb01"
    required: true

  db_system_db_home_db_version:
    title: "Database Version"
    type: enum
    enum:
      - 21.0.0.0
      - 19.0.0.0
      - 18.0.0.0
      - 12.2.0.0
      - 12.1.0.0
      - 11.2.0.0
    default: "19.0.0.0"

  db_system_db_home_database_admin_password:
    title: "Password for SYS, SYSTEM, PDB Admin and TDE Wallet"
    type: password
    confirmation: true
    required: true

  optional_tde_wallet_password:
    title: "Optional TDE wallet Password"
    type: boolean
      
  db_system_db_home_database_tde_wallet_password:
    title: "Optional password to open the TDE wallet"
    type: password
    confirmation: true
    visible: optional_tde_wallet_password

  db_system_db_home_database_db_workload:
    title: "Database workload type"
    type: enum
    enum:
      - OLTP
      - DW
    default: OLTP

  db_system_db_home_database_db_backup_config_auto_backup_enabled:
    title: "Enable automatic backups"
    type: boolean
    default: false

  db_system_db_home_database_db_backup_config_auto_backup_window:
    title: ""
    description: "Time window selected for initiating automatic backup for the database system. There are twelve available two-hour time windows. If no option is selected, a start time between 12:00 AM to 7:00 AM in the region of the database is automatically chosen. For example, if the user selects SLOT_TWO from the enum list, the automatic backup job will start in between 2:00 AM (inclusive) to 4:00 AM (exclusive). Example: SLOT_TWO"
    type: enum
    enum:
      - SLOT_ONE
      - SLOT_TWO
      - SLOT_THREE
      - SLOT_FOUR
      - SLOT_FIVE
      - SLOT_SIX
      - SLOT_SEVEN
      - SLOT_EIGHT
      - SLOT_NINE
      - SLOT_TEN
      - SLOT_ELEVEN
      - SLOT_TWELVE
    visible: db_system_db_home_database_db_backup_config_auto_backup_enabled
    default: SLOT_ONE

  db_system_db_home_database_db_backup_config_recovery_window_in_days:
    title: "Backup retention period (days)"
    description: "(Updatable) Number of days between the current and the earliest point of recoverability covered by automatic backups. This value applies to automatic backups only. After a new automatic backup has been created, Oracle removes old automatic backups that are created before the window. When the value is updated, it is applied to all existing automatic backups"
    type: enum
    enum:
      - 7
      - 15
      - 30
      - 45
      - 60
    default: 7
    visible: db_system_db_home_database_db_backup_config_auto_backup_enabled

  db_system_db_home_database_character_set:
    title: "Character Set"
    type: string
    default: "AL32UTF8"

  db_system_db_home_database_ncharacter_set: 
    title: "National Character Set"
    type: string
    default: "AL16UTF16"

# Variables not required to display to user

  db_system_source:
    type: string

  user_ocid:
    type: string

  fingerprint:
    type: string

  private_key_path:
    type: string

  region:
    type: string

# Hidden Tag Variables

  db_system_db_home_database_defined_tags:
    type: string

  db_system_db_home_database_freeform_tags:
    type: string

  db_system_db_home_defined_tags:
    type: string

  db_system_defined_tags:
    type: string
